ShopHome/urls.py
from argparse import Namespace
from django.contrib import admin
from django.core.checks import Debug
from django.urls import include, path
from main import views
from ShopHome.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog'))
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include('debug_toolbar.urls')),
    ]

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('product/', views.product, name='product')
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

goods/models.py
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        # goods_categories
        verbose_name = 'категории'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image =  models.ImageField(upload_to='goods_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка(%)')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Катeгория')
    class Meta:
        db_table = 'product'
        # goods_categories
        verbose_name = 'продукты'
        verbose_name_plural = 'продукты'


    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'

goods/views.py
from django.shortcuts import render

def catalog(request):
    context = {
        "title" : "Home - каталог",
        "goods" : [
        {'image': 'deps/images/goods/set of tea table and three chairs.jpg',
         'name': 'Чайный столик и три стула',
         'description': 'Комплект из трёх стульев и дизайнерский столик для гостинной комнаты.',
         'price': 150.00},

         {'image': 'deps/images/goods/set of tea table and two chairs.jpg',
         'name': 'Чайный столик и два стула',
         'description': 'Набор из стола и двух стульев в минималистическом стиле.',
         'price': 93.00},

         {'image': 'deps/images/goods/double bed.jpg',
         'name': 'Двухспальная кровать',
         'description': 'Кровать двухспальная с надголовником и вообще очень ортопедичная.',
         'price': 670.00},

         {'image': 'deps/images/goods/kitchen table.jpg',
         'name': 'Кухонный стол с раковиной',
         'description': 'Кухонный стол для обеда с встроенной раковиной и стульями.',
         'price': 365.00},

         {'image': 'deps/images/goods/kitchen table 2.jpg',
         'name': 'Кухонный стол с встройкой',
         'description': 'Кухонный стол со встроенной плитой и раковиной. Много полок и вообще красивый.',
         'price': 430.00},

         {'image': 'deps/images/goods/corner sofa.jpg',
         'name': 'Угловой диван для гостинной',
         'description': 'Угловой диван, раскладывается в двухспальную кровать, для гостинной и приема гостей самое то!',
         'price': 610.00},

         {'image': 'deps/images/goods/bedside table.jpg',
         'name': 'Прикроватный столик',
         'description': 'Прикроватный столик с двумя выдвижными ящиками (цветок не входит в комплект).',
         'price': 55.00},

         {'image': 'deps/images/goods/sofa.jpg',
         'name': 'Диван обыкновенный',
         'description': 'Диван, он же софа обыкновенная, ничего примечательного для описания.',
         'price': 190.00},

         {'image': 'deps/images/goods/office chair.jpg',
         'name': 'Стул офисный',
         'description': 'Описание товара, про то какой он классный, но это стул, что тут сказать...',
         'price': 30.00},

         {'image': 'deps/images/goods/plants.jpg',
         'name': 'Растение',
         'description': 'Растение для украшения вашего интерьера подарит свежесть и безмятежность обстановке.',
         'price': 10.00},

         {'image': 'deps/images/goods/flower.jpg',
         'name': 'Цветок стилизированный',
         'description': 'Дизайнерский цветок (возможно искусственный) для украшения интерьера.',
         'price': 15.00},

         {'image': 'deps/images/goods/strange table.jpg',
         'name': 'Прикроватный столик',
         'description': 'Столик, довольно странный на вид, но подходит для размещения рядом с кроватью.',
         'price': 25.00},
        ]
    }
    return render(request, 'goods/catalog.html', context)

def product(request):
    return render(request, 'goods/product.html')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

from goods.models import Categories


def index(request) -> HttpResponse:
    
    categories = Categories.object.all()

    context: dict[str, str] = {
        'title': 'Home - Главная',
        'content': 'Главная страница магазина "Home"',
        'categories' : categories
    }
    return render(request, 'main/index.html', context)


def about(request) -> HttpResponse:
    context: dict[str, str] = {
        'title' : 'Home - О нас',
        'content' : 'О нас',
        'text_on_page': 'Текст почему этот магазин такой крутой'
    }
    return render(request, 'main/about.html', context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                <input type="hidden" name="q" value="request.GET.q">
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>
    <!-- Карта товара -->
    {% for product  in goods %}
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            <img src= {% static product.image %} class="card-img-top" alt="...">
            <div class="card-body">
                <a href="../goods/product.html">
                    <p class="card-title">{{ product.name }}</p>
                </a>
                <p class="card-text text-truncate">{{ product.description }}</p>
                <p class="product_id">id: 02265</p>
                <div class="d-flex justify-content-between">
                    {% comment %} <p><s>100</s> $</p>
                    <p><strong>90.00 $</strong></p>
                    <span class="badge bg-warning text-dark">Скидка 10.00 %</span> {% endcomment %}
                    <p><strong> {{ product.price }}</strong></p>
                    <a href="#" class="btn add-to-cart">
                        <img class="mx-1" src= {% static "/deps/icons/cart-plus.svg" %} alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item disabled">
              <a class="page-link">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#">Next</a>
            </li>
        </div>
    </ul>
</nav>
{% endblock content %}
    


{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock footer %}

goods/templates/goods/product.html
{% extends "main/base.html" %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: 002654</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="../deps/images/goods/set of tea table and three chairs.jpg"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Цена: <strong>150.00 $</strong></p>
                <h5 class="card-title">Чайный столик и три стула</h5>
                <p class="card-text">Комплект из трёх стульев и дизайнерский столик для гостинной
                    комнаты.</p>
                <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
            </div>
        </div> 
    </div>   
{% endblock content %}

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block foot %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}


{% block content %}
    <div class="mt-5 pt-5 bg-black custom-shadow rounded">
        <h2 class="m-2 text-white"><strong>{{ content }}</strong></h2>
        <p class="m-2 text-white"> {{ text_on_page }}</p>
    </div>
   {% endblock content %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy, Maxim Yarmaluk 2024</p>
        </div>
    </footer>
{% endblock footer %}

main/templates/main/base.html
!{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block foot %} {% endblock  %}    
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="users/login.html">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% for category in categories %}
                          <li><a class="dropdown-item text-white" href="{% url 'catalog:index'%}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Maxim Yarmaluk 2024</p>
        </div>
    </footer>
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block foot %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}


{% block content %}
   <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock content %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy, Maxim Yarmaluk 2024</p>
        </div>
    </footer>
{% endblock footer %}

templates/about.html

<!-- Фрагмент для вставки в block content для страницы about-->
<!-- 
Если добавите много текста для описния и footer будет "налазить" поверх текста,
то уберите со страницы about вставку стиля для footer-a, и его отпустит"
-->

<div class="my-5 pt-5 px-2 pb-2 bg-white custom-shadow rounded">
    <h2 class="m-2"><strong>О нас</strong></h2>
    <p class="m-2" style="font-size: 1.2rem;">Текст о том какой классный этот интернет магазин.</p>
</div>

templates/other_files/notifications.html

<!-- Для non_field_erors  -->
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                Текст ошибок
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>

<!-- Оповещения в формах -->
<div class="alert alert-danger alert-dismissible fade show">Оишбка</div>

<!-- Для оповещений -->
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/other_files/sale_banner.html
<div class="container">
    <div class="d-flex flex-row overflow-x-auto m-0">
        <!-- Карта товара -->
            <div class="card rounded  custom-shadow-little m-1" style="max-width: 160px; min-width: 100px;">
                <img src="..." class="card-img-top" alt="">
                <span class="badge bg-danger badge-banner">%</span>
                <div class="card-body m-0 p-0 position-absolute">
                    <p class="card-title m-1"><a href="#">Название</a></p>
                    <p class="m-1"><strong>9.99 $</strong></p>
                </div>
            </div>
        <!-- карта все -->
    </div>
</div>